version: '3.7'
services:
  nginx:
    image: www-idnaconv-net
    build:
      context: .
      dockerfile: ci/container/Dockerfile
      target: dev
    ports:
      - 8090:8080
    volumes:
      - ./site-content:/usr/share/nginx/html
  hugo-server:
    image: klakegg/hugo:0.93.2
    command: server
    ports:
      - 1313:1313
    volumes:
      - ./source:/src
  hugo-build:
    image: klakegg/hugo:0.93.2-onbuild
    volumes:
      - ./source:/src
      - ./site-content:/target:rw
  hugo-shell:
    image: klakegg/hugo:0.93.2-alpine
    command: shell
    volumes:
      - ./source:/src
